[env]
RUST_TARGET_PATH = { value = "../linera-service", relative = true }

[build]
target = "wasm32-unknown-js-web"
rustflags = ["--cfg=web_sys_unstable_apis"]

[unstable]
build-std = ["panic_abort", "std"]
json-target-spec = true
