{
 "title": "Linera General",
 "tags": [ "linera" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Cluster Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network bytes TX/RX total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"default\", pod=~\"proxy.*|shards.*\"}[60s]) + rate(container_network_transmit_bytes_total{namespace=\"default\", pod=~\"proxy.*|shards.*\"}[60s]) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"default\", pod=~\"proxy.*|shards.*\", container=~\"linera.*\"}",
     "legendFormat": "{{pod}} - {{container}}"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\", pod=~\"proxy.*|shards.*\", container=~\"linera.*\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Container Total CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"proxy.*|shards.*\", container=~\"linera.*\"}[60s])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Scylla Memory Usage Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"scylla\"}",
     "legendFormat": "{{pod}} - {{container}}"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"scylla\"})",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Linera Execution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Block Execution Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(block_execution_latency_bucket{service=\"shards\"}[$__rate_interval])",
     "legendFormat": "{{pod}} - {{le}}"
    }
   ]
  },
  {
   "title": "Chains per Shard (24h)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (count_over_time({app=\"shards\"} |= `OpenChain` [24h]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Panics",
   "type": "table",
   "description": "Shard and proxy panics",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "{app=\"shards\"} |= `panic`"
    },
    {
     "expr": "{app=\"proxy\"} |= `panic`"
    }
   ]
  }
 ]
}