// Copyright (c) Zefchain Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

use linera_sdk::views::{linera_views, RegisterView, RootView, ViewStorageContext};

/// The application state storing random seeds generated by the contract.
#[derive(RootView)]
#[view(context = ViewStorageContext)]
pub struct RandomNumberState {
    pub seed1: RegisterView<u64>,
    pub seed2: RegisterView<u64>,
}
