name: Get Solc
description: Download `solc` from the Solidity Foundation's binary distribution.
inputs:
  version:
    default: "latest"
    description: Solc version (ex. `v0.8.15` or default `latest`).
    required: false
runs:
  using: "composite"
  steps:
    - name: Download
      run: $GITHUB_ACTION_PATH/solc_download.sh
      shell: bash
      env:
        SOLC_VERSION: ${{inputs.version}}
