// Copyright (c) Zefchain Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

//! Conversions from types declared in [`linera-sdk`] to types generated by [`wit-bindgen`].

use linera_views::batch::WriteOperation;

use crate::contract::wit::view_system_api as wit_system_api;

impl From<WriteOperation> for wit_system_api::WriteOperation {
    fn from(write_operation: WriteOperation) -> Self {
        match write_operation {
            WriteOperation::Delete { key } => wit_system_api::WriteOperation::Delete(key),
            WriteOperation::DeletePrefix { key_prefix } => {
                wit_system_api::WriteOperation::DeletePrefix(key_prefix)
            }
            WriteOperation::Put { key, value } => wit_system_api::WriteOperation::Put((key, value)),
        }
    }
}
