events {}

http {
    server {
            listen 80 http2;

            location / {
                    grpc_pass grpc://127.0.0.1:19100;
            }

            keepalive_timeout 10m 60s;
            grpc_read_timeout 10m;
            grpc_send_timeout 10m;
            client_header_timeout 10m;
            client_body_timeout 10m;
    }
}

