// Copyright (c) Zefchain Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

//! Conversions from types generated by [`wit_bindgen_rust`] to types declared in [`linera_sdk`].

use super::system;
use std::task::Poll;

impl From<system::PollLoad> for Poll<Result<Vec<u8>, String>> {
    fn from(poll_get: system::PollLoad) -> Poll<Result<Vec<u8>, String>> {
        match poll_get {
            system::PollLoad::Ready(bytes) => Poll::Ready(bytes),
            system::PollLoad::Pending => Poll::Pending,
        }
    }
}
