{
 "title": "Overview",
 "tags": [ "scylla-4.3" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "by", "label": "by", "query": "Cluster,DC,Instance,Shard" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(scylla_reactor_utilization, cluster)"
   },
   {
    "name": "dc",
    "label": "dc",
    "query": "label_values(scylla_reactor_utilization{cluster=~\"$cluster\"}, dc)"
   },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(scylla_reactor_utilization{cluster=~\"$cluster|$^\", dc=~\"$dc\"}, instance)"
   },
   {
    "name": "shard",
    "label": "shard",
    "query": "label_values(scylla_reactor_utilization,shard)"
   },
   { "name": "mount_point", "label": "Mount path", "query": "node_filesystem_avail_bytes" },
   { "name": "func", "label": "Function", "query": "sum,avg,max,min,stddev,stdvar" },
   { "name": "adhoc", "label": "ad hoc" },
   { "name": "dash_version", "query": "4-3" },
   { "name": "scylla_dash_version", "query": "4.3" },
   { "name": "monitoring_version", "query": "master" }
  ]
 },
 "panels": [
  { "title": "Cluster overview $cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "type": "text", "gridPos": { "h": 1, "w": 8, "x": 0, "y": 1 }, "options": { "content": "# " } },
  { "type": "text", "gridPos": { "h": 1, "w": 4, "x": 8, "y": 1 }, "options": { "content": "# " } },
  { "type": "text", "gridPos": { "h": 1, "w": 4, "x": 12, "y": 1 }, "options": { "content": "# " } },
  { "type": "text", "gridPos": { "h": 1, "w": 7, "x": 16, "y": 1 }, "options": { "content": "# " } },
  {
   "title": "# Nodes",
   "type": "stat",
   "description": "The number of nodes configured in the cluster.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"scylla\", cluster=~\"$cluster|$^\"})",
     "legendFormat": "Total Nodes"
    }
   ]
  },
  {
   "title": "Unreachable",
   "type": "stat",
   "description": "The number of unreachable nodes.\nUsually because a machine is down or unreachable.",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(count(scrape_samples_scraped{job=\"scylla\", cluster=~\"$cluster|$^\"}==0) OR vector(0))",
     "legendFormat": "Offline "
    }
   ]
  },
  {
   "title": "Inactive",
   "type": "stat",
   "description": "The number of joining and leaving nodes.\nThe number of nodes that are up but not actively part of the cluster, either because they are still joining or because they are leaving.",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(scylla_node_operation_mode!=3)OR vector(0)",
     "legendFormat": "Offline "
    }
   ]
  },
  {
   "title": "Manager",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(scylla_manager_task_active_count{type=~\"repair\",cluster=~\"$cluster|$^\"}) or on() vector(0)) + (sum(scylla_manager_task_active_count{type=~\"backup\",cluster=~\"$cluster|$^\"})*2 or on() vector(0)) + (sum(scylla_manager_server_current_version{}) or on() vector(-1))"
    }
   ]
  },
  {
   "title": "Avg Write",
   "type": "stat",
   "description": "Average Write Latency",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(scylla_storage_proxy_coordinator_write_latency_sum{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[60s]))/(sum(rate(scylla_storage_proxy_coordinator_write_latency_count{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[60s])) + 1)"
    }
   ]
  },
  {
   "title": "99% Write",
   "type": "stat",
   "description": "99% write Latency",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(scylla_storage_proxy_coordinator_write_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[60s])) by (le))"
    }
   ]
  },
  {
   "title": "Average Read",
   "type": "stat",
   "description": "Average Read Latency",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(scylla_storage_proxy_coordinator_read_latency_sum{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[60s]))/(sum(rate(scylla_storage_proxy_coordinator_read_latency_count{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[60s])) + 1)"
    }
   ]
  },
  {
   "title": "99% Read",
   "type": "stat",
   "description": "99% read Latency",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(scylla_storage_proxy_coordinator_read_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[60s])) by (le))"
    }
   ]
  },
  {
   "title": "Requests/s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "si:" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(scylla_transport_requests_served{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) + sum(rate(scylla_thrift_served{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s]))"
    }
   ]
  },
  {
   "title": "Load",
   "type": "stat",
   "description": "The percentage of the time during which Scylla utilized the CPU. Note that because Scylla does busy polling for some time before going idle, CPU utilization as seen by the operating system may be much higher. Your system is not yet CPU-bottlenecked until this metric is high.",
   "gridPos": { "h": 4, "w": 2, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(scylla_reactor_utilization{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"} )"
    }
   ]
  },
  {
   "title": "Timeouts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 21, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(scylla_storage_proxy_coordinator_write_timeouts{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[1m]))"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 4, "w": 1, "x": 23, "y": 2 }, "options": { "content": "# " } },
  {
   "title": "Active Alerts",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "job!=\"scylla_manager\",advisor=\"\"",
     "labelSelector": "description,dc,instance",
     "legendFormat": "{{description}}",
     "target": "Query",
     "type": "table"
    }
   ]
  },
  {
   "title": "Writes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "si:ops/s" }
   ],
   "targets": [
    {
     "expr": "$func(rate(scylla_storage_proxy_coordinator_write_latency_count{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Write Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(scylla_storage_proxy_coordinator_write_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[$__rate_interval])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(scylla_storage_proxy_coordinator_write_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[$__rate_interval])) by (le))",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "Reads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "si:ops/s" }
   ],
   "targets": [
    {
     "expr": "$func(rate(scylla_storage_proxy_coordinator_read_latency_count{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[$__rate_interval]))",
     "legendFormat": "Reads"
    }
   ]
  },
  {
   "title": "Read Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(scylla_storage_proxy_coordinator_read_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[$__rate_interval])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(scylla_storage_proxy_coordinator_read_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[$__rate_interval])) by (le))",
     "legendFormat": "99%"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 13 },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Advisor</h1>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 14 },
   "options": {
    "content": "### Balance\nAn Imbalance between shards or nodes may indicates a potential problem"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "job!=\"scylla_manager\", advisor!=\"\"",
     "labelSelector": "*",
     "legendFormat": "{{description}}",
     "target": "Query",
     "type": "table"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(abs(sum(scylla_transport_current_connections{instance=~\"[[node]]\" ,cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by (instance,shard)-scalar(avg(scylla_transport_current_connections{instance=~\"[[node]]\" ,cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"})))) - 8"
    }
   ]
  },
  {
   "title": "CQL Traffic",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(abs(rate(scylla_cql_updates{conditional=\"no\", instance=~\"[[node]]\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[1m]) - scalar(avg(rate(scylla_cql_updates{conditional=\"no\", instance=~\"[[node]]\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[1m]))))/scalar(stddev(rate(scylla_cql_updates{conditional=\"no\", instance=~\"[[node]]\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[1m]))+100))-3"
    },
    {
     "expr": "max(abs(rate(scylla_cql_inserts{conditional=\"no\", instance=~\"[[node]]\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[1m]) - scalar(avg(rate(scylla_cql_inserts{conditional=\"no\", instance=~\"[[node]]\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[1m]))))/scalar(stddev(rate(scylla_cql_inserts{conditional=\"no\", instance=~\"[[node]]\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[1m]))+100))-3"
    },
    {
     "expr": "max(abs(rate(scylla_cql_reads{conditional=\"no\", instance=~\"[[node]]\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[1m]) - scalar(avg(rate(scylla_cql_reads{conditional=\"no\", instance=~\"[[node]]\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[1m]))))/scalar(stddev(rate(scylla_cql_reads{conditional=\"no\", instance=~\"[[node]]\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[1m]))+100))-3"
    },
    {
     "expr": "max(abs(rate(scylla_cql_deletes{conditional=\"no\", instance=~\"[[node]]\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[1m]) - scalar(avg(rate(scylla_cql_deletes{conditional=\"no\", instance=~\"[[node]]\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[1m]))))/scalar(stddev(rate(scylla_cql_deletes{conditional=\"no\", instance=~\"[[node]]\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[1m]))+100))-3"
    }
   ]
  },
  {
   "title": "Node Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(histogram_quantile(0.99, sum(rate(scylla_storage_proxy_coordinator_write_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\"}[$__rate_interval])) by (instance, le)) -scalar(avg(histogram_quantile(0.99, sum(rate(scylla_storage_proxy_coordinator_write_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\"}[$__rate_interval])) by (instance,le))>0)))/ scalar(stddev(histogram_quantile(0.99, sum(rate(scylla_storage_proxy_coordinator_write_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\"}[$__rate_interval])) by (instance,le))>0)+100)-3"
    },
    {
     "expr": "max(histogram_quantile(0.99, sum(rate(scylla_storage_proxy_coordinator_read_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\"}[$__rate_interval])) by (instance, le)) -scalar(avg(histogram_quantile(0.99, sum(rate(scylla_storage_proxy_coordinator_read_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\"}[$__rate_interval])) by (instance,le))>0)))/ scalar(stddev(histogram_quantile(0.99, sum(rate(scylla_storage_proxy_coordinator_read_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\"}[$__rate_interval])) by (instance,le))>0)+100)-3"
    }
   ]
  },
  {
   "title": "Shard Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(histogram_quantile(0.99, sum(rate(scylla_storage_proxy_coordinator_write_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[$__rate_interval])) by (instance,shard, le)) -scalar(avg(histogram_quantile(0.99, sum(rate(scylla_storage_proxy_coordinator_write_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[$__rate_interval])) by (instance,shard,le))>0)))/ scalar(stddev(histogram_quantile(0.99, sum(rate(scylla_storage_proxy_coordinator_write_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[$__rate_interval])) by (instance,shard, le))>0)+100)-3"
    },
    {
     "expr": "max(histogram_quantile(0.99, sum(rate(scylla_storage_proxy_coordinator_read_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[$__rate_interval])) by (instance,shard, le)) -scalar(avg(histogram_quantile(0.99, sum(rate(scylla_storage_proxy_coordinator_read_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[$__rate_interval])) by (instance,shard,le))>0)))/ scalar(stddev(histogram_quantile(0.99, sum(rate(scylla_storage_proxy_coordinator_read_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[$__rate_interval])) by (instance,shard, le))>0)+100)-3"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "stat",
   "description": "A shard that reads more from the cache could be an indication for hot partition",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "((rate(scylla_cache_reads{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval]) - rate(scylla_cache_reads_with_misses{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval]))- scalar(avg(rate(scylla_cache_reads{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval]) - rate(scylla_cache_reads_with_misses{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval]))))/scalar(stddev(rate(scylla_cache_reads{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval]) - rate(scylla_cache_reads_with_misses{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval]))+100)-3"
    }
   ]
  },
  {
   "title": "SSTable",
   "type": "stat",
   "description": "A single shard that reads more from sstables, could be that a node is slow",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(abs(scylla_database_active_reads{instance=~\"[[node]]\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"} - scalar(avg(scylla_database_active_reads{instance=~\"[[node]]\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"})))/scalar(stddev(scylla_database_active_reads{instance=~\"[[node]]\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"})+0.001))-3"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }, "repeat": "dc" },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 24 },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Information for $dc</h1>"
  },
  {
   "title": "Load",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 1, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(scylla_reactor_utilization{instance=~\"[[node]]\",cluster=~\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"} )"
    }
   ]
  },
  {
   "title": "Disk Size by $by",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 1, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "Avg(node_filesystem_size_bytes{mountpoint=\"$mount_point\", dc=~\"$dc\", instance=~\"$node\"}) by ([[by]])-sum(node_filesystem_avail_bytes{mountpoint=\"$mount_point\",  dc=~\"$dc\", instance=~\"$node\"}) by ([[by]])",
     "legendFormat": "Avg Usage {{[[by]]}}"
    },
    {
     "expr": "avg(node_filesystem_size_bytes{mountpoint=\"$mount_point\", dc=~\"$dc\", instance=~\"$node\"}) by ([[by]])",
     "legendFormat": "Size {{[[by]]}}"
    }
   ]
  },
  {
   "title": "Writes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 26 },
   "yaxes": [
    { "format": "si:ops/s" }
   ],
   "targets": [
    {
     "expr": "$func(rate(scylla_storage_proxy_coordinator_write_latency_count{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[$__rate_interval])) by ([[by]])",
     "legendFormat": "Writes"
    },
    {
     "expr": "$func(rate(scylla_storage_proxy_coordinator_write_latency_count{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[$__rate_interval] offset 1d))",
     "legendFormat": "1 Day Ago"
    },
    {
     "expr": "$func(rate(scylla_storage_proxy_coordinator_write_latency_count{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[$__rate_interval] offset 1w))",
     "legendFormat": "1 Week Ago"
    }
   ]
  },
  {
   "title": "Write Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 26 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(scylla_storage_proxy_coordinator_write_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[$__rate_interval])) by ([[by]], le))",
     "legendFormat": "95% {{[[by]]}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(scylla_storage_proxy_coordinator_write_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[$__rate_interval])) by ([[by]], le))",
     "legendFormat": "99% {{[[by]]}}"
    }
   ]
  },
  {
   "title": "Reads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 26 },
   "yaxes": [
    { "format": "si:ops/s" }
   ],
   "targets": [
    {
     "expr": "$func(rate(scylla_storage_proxy_coordinator_read_latency_count{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[$__rate_interval])) by ([[by]])",
     "legendFormat": "Reads"
    },
    {
     "expr": "$func(rate(scylla_storage_proxy_coordinator_read_latency_count{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[$__rate_interval] offset 1d))",
     "legendFormat": "1 Day Ago"
    },
    {
     "expr": "$func(rate(scylla_storage_proxy_coordinator_read_latency_count{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[$__rate_interval] offset 1w))",
     "legendFormat": "1 Week Ago"
    }
   ]
  },
  {
   "title": "Read Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 26 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(scylla_storage_proxy_coordinator_read_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[$__rate_interval])) by ([[by]], le))",
     "legendFormat": "95% {{[[by]]}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(scylla_storage_proxy_coordinator_read_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[$__rate_interval])) by ([[by]], le))",
     "legendFormat": "99% {{[[by]]}}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "0*scylla_scylladb_current_version{cluster=~\"$cluster|$^\", dc=~\"$dc\"} + on (instance) group_left() scylla_node_operation_mode{cluster=~\"$cluster|$^\", dc=~\"$dc\"}"
    },
    {
     "expr": "avg(scylla_reactor_utilization{cluster=~\"$cluster\", dc=~\"$dc\"} ) by (instance)"
    }
   ]
  },
  {
   "title": "Running Compactions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "$func(scylla_compaction_manager_compactions{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Cache Hits/Misses",
   "type": "graph",
   "description": "The Hits and Misses",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 32 },
   "yaxes": [
    { "format": "si:ops/s" }
   ],
   "targets": [
    {
     "expr": "$func(rate(scylla_cache_row_hits{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]])",
     "legendFormat": "Hit {{[[by]]}}"
    },
    {
     "expr": "$func(rate(scylla_cache_row_misses{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]])",
     "legendFormat": "Misses {{[[by]]}}"
    }
   ]
  },
  {
   "title": "Read/Write Timeouts by [[by]]",
   "type": "graph",
   "description": "Requests that Scylla tried to write but timed out. Timeouts are counted in the node that received the request (the coordinator), not at the replicas.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 32 },
   "yaxes": [
    { "format": "si:ops/s" }
   ],
   "targets": [
    {
     "expr": "$func(rate(scylla_storage_proxy_coordinator_write_timeouts{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[$__rate_interval])) by ([[by]])",
     "legendFormat": "Writes timeout {{[[by]]}}"
    },
    {
     "expr": "$func(rate(scylla_storage_proxy_coordinator_read_timeouts{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])+rate(scylla_storage_proxy_coordinator_cas_read_timeouts{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])+rate(scylla_storage_proxy_coordinator_range_timeouts{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]])",
     "legendFormat": "Read  timeout {{[[by]]}}"
    }
   ]
  },
  { "title": "Your panels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 39 },
   "options": {
    "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Your Panels</h1>"
   }
  },
  {
   "title": "Your Graph here",
   "type": "graph",
   "description": "This graph panel was left empty on purpose for ad-hoc usage. Change it when needed. Pay attention that changes to the panel will not be saved.\n\nIf you do need a panel that can be saved, create a new dashboard, or edit the panel inside the json file",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "si:ops/s" }
   ]
  },
  {
   "title": "Your Graph here",
   "type": "graph",
   "description": "This graph panel was left empty on purpose for ad-hoc usage. Change it when needed. Pay attention that changes to the panel will not be saved.\n\nIf you do need a panel that can be saved, create a new dashboard, or edit the panel inside the json file",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "si:ops/s" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 47 },
   "options": {
    "content": "<div style=\"color:#5881c2; border-bottom: 0px solid #5881c2;\">Scylla Monitoring version - master</div> <div style=\"\"><a href=\"https://github.com/scylladb/scylla-monitoring/issues/new?body=scylla-version%3D[[scylla_dash_version]]%0Amonitoring-version%3D[[monitoring_version]]%0Adashboard%3D${__dashboard.uid}\" target=\"_blank\">\n<input title=\"Report an issue with Scylla Monitoring\" type=\"button\" style=\"background-color:#306EE6;color:white;border-radius: 15px;font-size:14px;line-height:22px;padding:2px\" value=\"&nbsp;Report an issue on this page&nbsp;\"></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"/render/d/${__dashboard.uid}?orgId=1&from=${__from}&to=${__to}&width=1000&height=2500\" target=\"_blank\" download=\"dashboard_${__dashboard.uid}-${__from:date:iso}.png\"><input title=\"Make a Screenshot\" type=\"button\" style=\"background-color:#306EE6;color:white;border-radius: 15px;font-size:14px;line-height:22px;padding:2px\" value=\"&nbsp;&nbsp;&nbsp;Screenshot&nbsp;&nbsp;&nbsp;\"></input></a></span></div>"
   }
  }
 ]
}