// Copyright (c) Zefchain Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

//! Conversions from types generated by [`wit_bindgen_rust`] to types declared in [`linera_sdk`].

use super::service;
use linera_sdk::{ChainId, CryptoHash, QueryContext};

impl From<service::QueryContext> for QueryContext {
    fn from(application_context: service::QueryContext) -> Self {
        QueryContext {
            chain_id: ChainId(application_context.chain_id.into()),
        }
    }
}

impl From<service::CryptoHash> for CryptoHash {
    fn from(crypto_hash: service::CryptoHash) -> Self {
        CryptoHash::from([
            crypto_hash.part1,
            crypto_hash.part2,
            crypto_hash.part3,
            crypto_hash.part4,
            crypto_hash.part5,
            crypto_hash.part6,
            crypto_hash.part7,
            crypto_hash.part8,
        ])
    }
}
