// Copyright (c) Zefchain Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

//! Types for the exported futures for the service endpoints.
//!
//! Each type is called by the code generated by [`wit_bindgen_rust`] when the host calls the guest
//! WASM module's respective endpoint. This module contains the code to forward the call to the
//! service type that implements [`linera_sdk::Service`].

use crate::{
    service::{self, system_api},
    ExportedFuture, Service, ServiceLogger,
};
use serde::{de::DeserializeOwned, Serialize};
use std::marker::PhantomData;

/// Future implementation exported from the guest to allow the host to call
/// [`Application::query_application`].
///
/// Loads the `Application` state and calls its
/// [`query_application`][Application::query_application] method.
pub struct QueryApplication<Application> {
    future: ExportedFuture<Result<Vec<u8>, String>>,
    _application: PhantomData<Application>,
}

impl<Application> QueryApplication<Application>
where
    Application: Service + Default + DeserializeOwned + Serialize,
{
    /// Creates the exported future that the host can poll.
    ///
    /// This is called from the host.
    pub fn new(context: service::QueryContext, argument: Vec<u8>) -> Self {
        ServiceLogger::install();

        QueryApplication {
            future: ExportedFuture::new(async move {
                let application: Application = system_api::load().await;
                application
                    .query_application(&context.into(), &argument)
                    .await
                    .map_err(|error| error.to_string())
            }),
            _application: PhantomData,
        }
    }

    /// Polls the future export from the guest.
    ///
    /// This is called from the host.
    pub fn poll(&self) -> service::PollQuery {
        self.future.poll()
    }
}
