// Copyright (c) Zefchain Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

//! Internal module with code generated by [`wit-bindgen`](https://github.com/jvff/wit-bindgen).

#![allow(missing_docs)]

// Export the service interface.
wit_bindgen_guest_rust::export!(
    export_macro = "export_service"
    types_path = "service::wit_types"
    reexported_crate_path = "wit_bindgen_guest_rust"
    "service.wit"
);
