// Copyright (c) Zefchain Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

//! Internal module with code generated by [`wit-bindgen`](https://github.com/jvff/wit-bindgen).

#![allow(missing_docs)]

// Export the service interface.
wit_bindgen_guest_rust::export!("service.wit");

use super::__service_handle_query;

/// Implementation of the service WIT entrypoints.
pub struct Service;

impl service::Service for Service {
    fn handle_query(argument: Vec<u8>) -> Result<Vec<u8>, String> {
        unsafe { __service_handle_query(argument) }
    }
}
