initialize: func(argument: list<u8>) -> result<tuple<>, string>
execute-operation: func(operation: list<u8>) -> result<tuple<>, string>
execute-message: func(message: list<u8>) -> result<tuple<>, string>
handle-application-call: func(argument: list<u8>) -> result<list<u8>, string>
finalize: func() -> result<tuple<>, string>
