chain-id: func() -> chain-id
application-id: func() -> application-id

resource load {
    static new: func() -> load
    poll: func() -> poll-load
}

variant poll-load {
    pending,
    ready(expected<list<u8>, string>),
}

record application-id {
    bytecode: bytecode,
    creation: effect-id,
}

type bytecode = effect-id

record effect-id {
    chain-id: chain-id,
    height: block-height,
    index: u64,
}

type chain-id = hash-value
type block-height = u64

record hash-value {
    part1: u64,
    part2: u64,
    part3: u64,
    part4: u64,
    part5: u64,
    part6: u64,
    part7: u64,
    part8: u64,
}
