resource handle-query {
    static new: func(
        context: query-context,
        argument: list<u8>,
    ) -> handle-query

    poll: func() -> poll-application-query-result
}

record query-context {
    chain-id: chain-id,
}

type chain-id = crypto-hash

variant poll-application-query-result {
    pending,
    ready(result<list<u8>, string>),
}

record crypto-hash {
    part1: u64,
    part2: u64,
    part3: u64,
    part4: u64,
}
