handle-query: func(context: query-context, argument: list<u8>) -> result<list<u8>, string>

record query-context {
    chain-id: chain-id,
}

type chain-id = crypto-hash

record crypto-hash {
    part1: u64,
    part2: u64,
    part3: u64,
    part4: u64,
}
