chain-id: func() -> chain-id
application-id: func() -> application-id
application-parameters: func() -> list<u8>
read-system-balance: func() -> system-balance
read-system-timestamp: func() -> timestamp

log: func(message: string, level: log-level)

enum log-level {
    trace,
    debug,
    info,
    warn,
    error,
}

resource load {
    static new: func() -> load
    poll: func() -> poll-load
}

variant poll-load {
    pending,
    ready(list<u8>),
}

resource load-and-lock {
    static new: func() -> load-and-lock
    poll: func() -> poll-load-and-lock
}

variant poll-load-and-lock {
    pending,
    ready(option<list<u8>>),
}

store-and-unlock: func(value: list<u8>) -> bool

resource lock {
    static new: func() -> lock
    poll: func() -> poll-lock
}

variant poll-lock {
    pending,
    ready-locked,
    ready-not-locked,
}

resource read-key-bytes {
    static new: func(key: list<u8>) -> read-key-bytes
    poll: func() -> poll-read-key-bytes
}

variant poll-read-key-bytes {
    pending,
    ready(option<list<u8>>),
}

resource find-keys {
    static new: func(prefix: list<u8>) -> find-keys
    poll: func() -> poll-find-keys
}

variant poll-find-keys {
    pending,
    ready(list<list<u8>>),
}

resource find-key-values {
    static new: func(prefix: list<u8>) -> find-key-values
    poll: func() -> poll-find-key-values
}

variant poll-find-key-values {
    pending,
    ready(list<tuple<list<u8>,list<u8>>>),
}

variant write-operation {
    delete(list<u8>),
    deleteprefix(list<u8>),
    put(tuple<list<u8>,list<u8>>),
}

resource write-batch {
    static new: func(key: list<write-operation>) -> write-batch
    poll: func() -> poll-unit
}

variant poll-unit {
    pending,
    ready,
}

resource try-call-application {
    static new: func(
        authenticated: bool,
        application: application-id,
        argument: list<u8>,
        forwarded-sessions: list<session-id>,
    ) -> try-call-application

    poll: func() -> poll-call-result
}

resource try-call-session {
    static new: func(
        authenticated: bool,
        session: session-id,
        argument: list<u8>,
        forwarded-sessions: list<session-id>,
    ) -> try-call-application

    poll: func() -> poll-call-result
}

variant poll-call-result {
    pending,
    ready(call-result),
}

record call-result {
    value: list<u8>,
    sessions: list<session-id>,
}

record session-id {
    application-id: application-id,
    kind: u64,
    index: u64,
}

record application-id {
    bytecode-id: bytecode-id,
    creation: effect-id,
}

type bytecode-id = effect-id

record effect-id {
    chain-id: chain-id,
    height: block-height,
    index: u64,
}

type chain-id = crypto-hash
type block-height = u64
type timestamp = u64

record crypto-hash {
    part1: u64,
    part2: u64,
    part3: u64,
    part4: u64,
    part5: u64,
    part6: u64,
    part7: u64,
    part8: u64,
}

record system-balance {
    lower-half: u64,
    upper-half: u64,
}
