[package]
name = "linera-web"
description = "The Linera Web client"
readme = "README.md"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[package.metadata.cargo-machete]
# Used through `#[serde(with = "serde_bytes")]`, which `cargo-machete` cannot see.
ignored = ["serde_bytes"]

[lints.clippy]
pedantic = "warn"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook.workspace = true
futures.workspace = true
hex.workspace = true
js-sys.workspace = true
serde.workspace = true
serde-wasm-bindgen.workspace = true
serde_bytes.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-web.workspace = true
tsify.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true

[dependencies.tracing-subscriber]
features = ["ansi", "fmt", "std"]
workspace = true

[dependencies.linera-base]
features = ["web"]
workspace = true

[dependencies.linera-chain]
features = ["web"]
workspace = true

[dependencies.linera-client]
default-features = false
features = ["web", "wasmer", "indexed-db"]
workspace = true

[dependencies.linera-core]
features = ["web", "wasmer"]
workspace = true

[dependencies.linera-execution]
features = ["web", "wasmer"]
workspace = true

[dependencies.linera-faucet-client]
workspace = true

[dependencies.linera-rpc]
features = ["web"]
workspace = true

[dependencies.linera-sdk]
workspace = true

[dependencies.linera-storage]
features = ["web", "wasmer"]
workspace = true

[dependencies.linera-views]
features = ["web", "indexeddb"]
workspace = true

[dependencies.web-sys]
features = [
    "console",
    "Lock",
    "LockManager",
    "LockOptions",
    "Navigator",
    "Window",
]
workspace = true
