// Copyright (c) Zefchain Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

//! Conversions from types declared in [`linera_sdk`] to types generated by [`wit_bindgen_rust`].

use super::contract;
use linera_sdk::{
    ApplicationCallResult, Destination, ExecutionResult, HashValue, Session, SessionCallResult,
};
use std::task::Poll;

impl From<HashValue> for contract::HashValue {
    fn from(hash_value: HashValue) -> Self {
        let parts = <[u64; 8]>::from(hash_value);

        contract::HashValue {
            part1: parts[0],
            part2: parts[1],
            part3: parts[2],
            part4: parts[3],
            part5: parts[4],
            part6: parts[5],
            part7: parts[6],
            part8: parts[7],
        }
    }
}

impl From<ApplicationCallResult> for contract::ApplicationCallResult {
    fn from(result: ApplicationCallResult) -> Self {
        let create_sessions = result
            .create_sessions
            .into_iter()
            .map(contract::Session::from)
            .collect();

        contract::ApplicationCallResult {
            create_sessions,
            execution_result: result.execution_result.into(),
            value: result.value,
        }
    }
}

impl From<Session> for contract::Session {
    fn from(new_session: Session) -> Self {
        contract::Session {
            kind: new_session.kind,
            data: new_session.data,
        }
    }
}

impl From<SessionCallResult> for contract::SessionCallResult {
    fn from(result: SessionCallResult) -> Self {
        contract::SessionCallResult {
            inner: result.inner.into(),
            data: result.data,
        }
    }
}

impl From<ExecutionResult> for contract::ExecutionResult {
    fn from(result: ExecutionResult) -> Self {
        let effects = result
            .effects
            .into_iter()
            .map(|(destination, effect)| (destination.into(), effect))
            .collect();

        let subscribe = result
            .subscribe
            .into_iter()
            .map(|(channel_id, chain_id)| (channel_id.0, chain_id.0.into()))
            .collect();

        let unsubscribe = result
            .unsubscribe
            .into_iter()
            .map(|(channel_id, chain_id)| (channel_id.0, chain_id.0.into()))
            .collect();

        contract::ExecutionResult {
            effects,
            subscribe,
            unsubscribe,
        }
    }
}

impl From<Destination> for contract::Destination {
    fn from(destination: Destination) -> Self {
        match destination {
            Destination::Recipient(chain_id) => contract::Destination::Recipient(chain_id.0.into()),
            Destination::Subscribers(channel_id) => {
                contract::Destination::Subscribers(channel_id.0)
            }
        }
    }
}

impl From<Poll<Result<ExecutionResult, String>>> for contract::PollExecutionResult {
    fn from(poll: Poll<Result<ExecutionResult, String>>) -> Self {
        use contract::PollExecutionResult;
        match poll {
            Poll::Pending => PollExecutionResult::Pending,
            Poll::Ready(Ok(result)) => PollExecutionResult::Ready(Ok(result.into())),
            Poll::Ready(Err(message)) => PollExecutionResult::Ready(Err(message)),
        }
    }
}

impl From<Poll<Result<ApplicationCallResult, String>>> for contract::PollCallApplication {
    fn from(poll: Poll<Result<ApplicationCallResult, String>>) -> Self {
        use contract::PollCallApplication;
        match poll {
            Poll::Pending => PollCallApplication::Pending,
            Poll::Ready(Ok(result)) => PollCallApplication::Ready(Ok(result.into())),
            Poll::Ready(Err(message)) => PollCallApplication::Ready(Err(message)),
        }
    }
}

impl From<Poll<Result<SessionCallResult, String>>> for contract::PollCallSession {
    fn from(poll: Poll<Result<SessionCallResult, String>>) -> Self {
        use contract::PollCallSession;
        match poll {
            Poll::Pending => PollCallSession::Pending,
            Poll::Ready(Ok(result)) => PollCallSession::Ready(Ok(result.into())),
            Poll::Ready(Err(message)) => PollCallSession::Ready(Err(message)),
        }
    }
}
