name: Benchmarks

on:
  # TODO(#5173): reactivate this rule
  # push:
  #   branches: [ main, 'devnet_*', 'testnet_*' ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_RETRY: 10

jobs:
  benchmark:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Clear up some space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
    - name: Install Protoc
      run: |
        set -euo pipefail
        PB_VER=34.1
        curl -fsSL -o /tmp/protoc.zip \
          "https://github.com/protocolbuffers/protobuf/releases/download/v${PB_VER}/protoc-${PB_VER}-linux-x86_64.zip"
        sudo unzip -o /tmp/protoc.zip -d /usr/local
        protoc --version
    - name: Run benchmarks
      run: |
        cargo bench -p linera-service
